# Variables
@baseUrl = http://localhost:3333

# Health check
# @name HealthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name GetRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name CreateRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Nova question",
  "description": "descrição"
}

###

@roomId = {{CreateRoom.response.body.$.roomId}}

###

# Get Room Questions
# @name GetRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name CreateQuestion
POST {{baseUrl}}/rooms/20b8b650-62c7-4286-cca6-c3693b7c8811/create-question
Content-Type: application/json

{
  "question": "Como os caminhões funcionam ?"
}

